sessionKey 	=  "TWc9PSZ5azdObjM3eEJJTVlJQUNjTStlSzU3ajhGWC8veUI3T1VycUVrc3Y4dmkzVlgvei9ZTW91T1JiTzJycTZHMHRJVjBDZ1hCSWMwSERSREpFUkdvNy9wQStZRGF2VktkVVhKN2V1LzU1WGpKa0hpYzFidG96UkdZQXdITWFDenZJVVZ2dVl3aVBHT1IyK3NiZnJJR0hWb1plRER5Z2hPM1RHc1BhWWVhdUlLbjg1MlkzTnVDTTVZNjFtbjBYQndQVmF0THhWVk85b29hMFV2OUx6NVRFMkFpZlAyZStaU0dCQUovQWVtQTVuR2xDNm9NaU0yL3RTdXV5aGhXVXprN0dOOU1EU3lVcy9VMUk2SVpzK0FHYUE5TExLZGFUVmY5aEdJQVJmcjJVUnBlc3ZhVENxRzFoY3A1UHFOSDlIYXdZM1RpQ2sxb2FKdXJTZ2pGMlRvNzdUZFFOK2ZlTXZVdGx0cnFFUWpuSzVtTU1GTzhWejZKcWw3all0VlM1aVRQcFdZdHpQK0Q4MGdGZUhEMnN0d0xURThOY2gwMUt6QXpDRVZJcllSQXBVZmhKMzROUTUyU21EclE1VE5Lb1E3TVlPSU9zZE5xRlNIcnJ3eXhWc2xIbTBvcnBnSHlLMlBYQnEwYm5kQSt4dXVMK0VTTmVqMWpGQThzUjdiTDdNU1lXVFhWaVpxQ3hEK3E0R2ZWZlo3ek1selBWbDJiN3VnMlJrRE1DTXRYeXJDeGhWK0dqeGJqRWVWNTdBNW9ZcWkvdmRQU0NNMmszZlNKaGtBSG1icFExdkF6Mjh4TDFydXFyNk5GZmZTSTkyaVhYaE1XeTZ6a1JDaEFzdlViTWVyajRpcWo5Z2xKOTBBOU9HNEdxVGw2MGR5STlFdGVXYnRtaVJ6ZTY2OGdqNVNiMkhpUHZrL0VldnlnMlVhV0pKQkZnenE1Q3RXMkI2Qi9WTVUxK2VTdUoyam1hWVB2Um9Obyt0S2cvQUxrM3Y4dWxaMHJmMmdLVlJMLytHUWFYNVoxWElqSk1kRnlnOEpHQ0JscVZWN0FjNHJ1aDBTK1JlenRUODdVSUx1RmtZOERlUEFaYllETld4eit0ZU8vL3RGcFpST0lSYWxKcHJTSFI5WmRab1hRR2JHM0c4dHNmdTlmVFk0Y2FVeDkwbm9xWk1KSTNDb28rWTMxSjVaZnZCN0kxdWIzWGEwVCswZDVwV3BIVnh4eEpyRUdRVEovT3dTRW5WdW05U20vd1hTTCtld0piRERRZGN0ckRoa0NKS212K1gmeHlYTkcvdFJNZmtBNzJDTUQ1SUt3cmJFUFlFPQ=="

csrfToken	= "1d7df6fbd5e80a9b140abd4196ccf0d6"
MaxThread	=6
MaxPage		=2
MaxRetry   	=3
StartRegion =1
ProxyTestUrl= "https://ads.tiktok.com/business/creativecenter/music/pc/en"
NginxProxy  = "http://nft.skymeta.pro/proxys?url=,https://mangaverse.top/proxys?url="

[Elasticsearch]
    addr        = "http://localhost:9200"
    user 		= ""
    password	= ""

[Postgres]
	addr		= "127.0.0.1:5432"
	user 		= "manga"
	password	= "QMU4gPoEKHQW"
	database	= "tiktok_audios"
